# Generated by Django 3.1.2 on 2020-10-11 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('collaborators', models.ManyToManyField(default=1, related_name='collaborators', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=100)),
                ('haveDeadline', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(default='2020-10-11 08:53')),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('work_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.work')),
            ],
        ),
    ]
